// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZS8EHkyTMDvFNZkV11XYWMNISF598_So',
    appId: '1:378081741689:web:61285155b8332fb8a8fda8',
    messagingSenderId: '378081741689',
    projectId: 'touch-tracking-expiment',
    authDomain: 'touch-tracking-expiment.firebaseapp.com',
    storageBucket: 'touch-tracking-expiment.appspot.com',
    measurementId: 'G-XRBH6Z04MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYqdG_wFd8N257oZPai2_473E7phRycfM',
    appId: '1:378081741689:android:d230c3289e4ec30ea8fda8',
    messagingSenderId: '378081741689',
    projectId: 'touch-tracking-expiment',
    storageBucket: 'touch-tracking-expiment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbXKwvSo_QY8MenTfBVm9n2VMFJdliCyk',
    appId: '1:378081741689:ios:ccfe9b450e80f308a8fda8',
    messagingSenderId: '378081741689',
    projectId: 'touch-tracking-expiment',
    storageBucket: 'touch-tracking-expiment.appspot.com',
    iosClientId:
        '378081741689-g0m7jpt12cihd92bre13vilb7ata3kis.apps.googleusercontent.com',
    iosBundleId: 'com.zeyus.touchtracker',
  );
}
